/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const action1_Logic = require('./code/action1-logic');

class DAPService1 extends LCAPApplicationService {
    async init() {

        this.on('Action1', async (request, next) => {
            return action1_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    DAPService1
};